services:
  wordpress:
    # TODO: figure out service discovery namespacing to match AWS
    platform: linux/amd64
    depends_on:
      - database
    image: wordpress:6.6-php8.3-fpm-alpine  # Latest version of WordPress with PHP 8.3
    ports:
      - "9000:9000"
    env_file: .wordpress.env
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
    volumes:
      - ./site:/var/www/html

  database:
    platform: linux/amd64
    image: mysql:8.0.36-debian  # Version compatible with AWS Aurora
    ports:
      - "3306:3306"
    env_file: .database.env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress

  reverse-proxy:
    platform: linux/amd64
    depends_on:
      - wordpress
    #image: nginx:1.26-alpine  # Latest version of NGINX
    build:
      context: ./services/reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./services/reverse-proxy/root/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/var/www/html:ro
