name: Build Container Images

on:
  push:
    branches: [ main ]
    paths: [ 'services/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'services/**' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::816069151329:role/gha-ecr-push-role-oidc
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ravenoak/wp-nginx-fcgi:latest
          file: services/reverse-proxy/Dockerfile
          context: services/reverse-proxy

      - name: Build and push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: true
          sbom: true
          tags: ravenoak/wp-nginx-fcgi:latest
          file: services/reverse-proxy/Dockerfile
          context: services/reverse-proxy
